# CANVAS
CANVAS_WIDTH = 1600
CANVAS_HEIGHT = 1000
CAKE_PORTION = 2 / 3
INFO_PORTION = 1 - CAKE_PORTION
AREA_GAMMA = 6
RATIO_GAMMA = 3
FONT_SIZE = 22
SMALL_FONT_SIZE = 14
CAKE_SCALE = 30  # pixels per cm

## COLORS
CANVAS_BG = "#FCF1E3"
CAKE_CRUST = "#FDAE53"
CAKE_INTERIOR = "#FEDE8C"

# LOGIC
MIN_CAKE_ANGLE_DEGREE = 15
MIN_CAKE_INTERIOR_RATIO = 5 / 10
CRUST_SIZE = 1
MIN_PIECE_AREA = 10

MIN_PIECE_AREA_PER_CHILD = 10
MAX_PIECE_AREA_PER_CHILD = 50

# CONSTANTS
TOL = 1e-5
PIECE_SPAN_TOL = 0.5
